### PR TITLE
Add position sticky to the header 

### PR DESCRIPTION
**Pull request by NalianAchei2020**
# 📝 Accomplishments
*  change the header to position sticky.
*  Change the text color of the nav bar.
*  Update the README file.
*  Adjusted the background image to match the Figma design.
*  Added font and color to text as it is in the design.
*  Removed non-required sections.

### CODE REVIEW

**Review by roshan-bajgain — CHANGES_REQUESTED** [review]
Hi @NalianAchei2020, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
## Required Changes ♻️
- [ ] I cannot leave comment there so I am leaving it here please implement it.
- [ ] The container of the section is a header tag, Typically the `header` tag is used as a page header. Please remove section tag from header and use only header.
- [ ] For better semantic reason please wrap logo with `a` tag that is on the left side. Please replace `h2` tag with `a` tag.
- [ ] There is hamburger button is on the right please wrap only the hamburger buttons with nav tag for semantics reason, and the right position for convention and user experience for mobile devices.
- [ ] [Optioinal] For now you can remove the navlink as you will implement it on desktop verson.
- [ ] We use `h1` tag for the main page heading so please use `h1` tag for the main title (e.g., "I'm Marianne ...") for better semantic reason.
- [ ] In this project you need to do only the first section. So please remove other section for now. You will implement the rest other in next project.
### Thing to implement in this project
fimga
- [ ] As requested in the project requirement you should stick to the design as much as possible like color, font, size, background etc. 
- [ ] I would suggest you please use the same color for the content in the design. And there is background image on the right side of the design please implement it.
- [ ] I would suggest you please download the socail medai icons and use it on your page it helps to stick to the design as much as possible.
- [ ] If you see the design then there is round border at button-left side of the design. Also provide the background color for whole height 
### Your desgin
his


### Figma design
fimga



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by NalianAchei2020** [comment]
Hi @roshan-bajgain 
Please can you help on how to place the background image as it is in the design? I have been stuck on that for a while
image

**Comment by roshan-bajgain** [comment]
Hello @NalianAchei2020, please use the 
`select_class {
 background-image: url("image_url");
}`
Then please use the position to fix the image where you want to use.

**Review by Kossi-stack — APPROVED** [review]
## Status: Approved ✔️

**Hi @NalianAchei2020,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c

You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ Linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Optional suggestions

- [OPTIONAL] Kindly use your name in the `h1` tag

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Pull request merged**
